version: "3.3"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8182:8080
    depends_on:
      - db


