[package]
name = "reputation-aggregator-model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.10.2"
bigdecimal = "0.2.2"
chrono = "0.4.19"
serde_json = "1.0"
