name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release/*
jobs:
  build:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        #[ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install last stable Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions/setup-node@v3
        with:
          node-version: 12.18.4
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        env:
          SQLX_OFFLINE: true
        with:
          command: check
          args: --workspace
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features client -p reputation-aggregator-model
